# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - '*' 

pool:
  vmImage: 'ubuntu-latest'

variables:
  solutionPath: ./Source/Sundew.Quantities.sln
  buildConfiguration: 'Release'
  source: 'https://api.nuget.org/v3/index.json'
  pushSource: 'null'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: 5.x

- script: dotnet build $(solutionPath) --verbosity normal --configuration $(buildConfiguration) -p:'SbpSourceName=$(Build.SourceBranch)' -p:'SbpProductionSource=refs/heads/master|$(source)' -p:'SbpIntegrationSource=refs/heads/release/.+|$(source)' -p:'SbpAllowLocalSource=false' -p:'SbpEnablePublish=false' -p:'SbpPublishLogFormats=##vso[task.setvariable variable=pushSource]{2}'
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test $(solutionPath) --verbosity d --configuration $(buildConfiguration) --no-build
  displayName: 'dotnet test $(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    Contents: '**/*.nupkg'
    TargetFolder: $(Build.ArtifactStagingDirectory)

- script: dotnet nuget push '$(Build.ArtifactStagingDirectory)/**/*.nupkg' -s '$(pushSource)' -k '$(SbpApiKey)'
  condition: ne(variables.pushSource, 'null')
  displayName: 'dotnet nuget push'
